---
abstract: 'Allows pointcut-targetted NYTProf profiling'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Aspect::Library::NYTProf
name: Aspect-Library-NYTProf
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Aspect::Modular: 1.00
  Devel::NYTProf: 3.01
  perl: 5.8.2
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/Aspect-Library-NYTProf
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/Aspect-Library-NYTProf
version: 1.00
